### PR TITLE
Add color picker to BBeditor

### PR DESCRIPTION
**Pull request by beaver-dev**
New tags available : Colors, center, right, justify, center.
New icons and small design improvements.

### CODE REVIEW

**Comment by beaver-dev** [comment]
Size is now 26/27 px for all themes, I didn't find where it came from so it's not very clean, but better than before.
And what exactly issue do you have with other themes and the color picker ? I tested on Chromium and Firefox latest builds (on Mac OS) and everything went fine.

**Comment by adaur** [comment]
Many thanks. Actually, if you hover the color picker and you move the pointer away, the color picker will stay out as long as you don't re-hover it whereas it should close itself. I'll see if I can fix that (but if you have an easy fix, don't hesitate!)

**Comment by adaur** [comment]
I'd like the same thing than on the demo: a clic to open the menu, an other one to close it (or a color chosen)

**Comment by beaver-dev** [comment]
Oh that's not a bug, i coded it that way :P no need for another pull request, just replace line 34 of `js/bbeditor.js` with the following :

``` javascript
document.write("<img class=\"toolbar-icon\" src=\""+baseUrl+"/img/bbeditor/eyedropper.png\" name=\"btnColor\" title=\"Color\" onClick=\"toggleColorpicker()\">");
```

and that's it !

**Comment by adaur** [comment]
Perfect :-) One last thing: do you think it is possible to put the pointer within the tags?

Like I click, and I arrive [center]HERE[/center]

The FluxToolbar does this I believe.

**Comment by beaver-dev** [comment]
Yeah I thought about it, I'm reading the FluxToolbar source code to implement this functionality in a further pull request.
Should be in a few days as usual :)

**Comment by adaur** [comment]
Don't hurry ;-)

**Pull request merged**
