### PR TITLE
Fix csrf create token

### PR DESCRIPTION
**Pull request by Baumzebra**
The current way to create the token throws folowing warning.

`Warning: rand() expects parameter 2 to be integer, float given in ...\featherbb\featherbb\Middleware\Csrf.php on line 237`

### CODE REVIEW

**Comment by beaver-dev** [comment]
Everything works fine with your modification, PR accepted!
Thanks for your time ;)

**Comment by adaur** [comment]
Thank you!

**Comment by franzliedke** [comment]
Isn't `random_bytes()` a PHP 7 function?

**Comment by adaur** [comment]
Good point, that may be what I didn't add it in the first place @beaver-dev

**Comment by Poffen** [comment]
FYI. There is a legacy workaround for the PHP 7 random_bytes(), which works for PHP 5.2-5.6. More info on the [official PHP website](http://php.net/manual/en/function.random-bytes.php) and [here](https://github.com/paragonie/random_compat).

Putte

**Comment by adaur** [comment]
OK, thanks for the info. If we use it for password hashing, it could be worth it.

**Pull request merged**
