### PR TITLE
Tweaking message function to use Slim methods

### PR DESCRIPTION
**Pull request by peloyeje**
Don’t pay attention to header modifs, my bad ..

### CODE REVIEW

**Comment by adaur** [comment]
Thanks for the pull request. 

However, why did you remove the dontStop tweak? Without it, an Exit exception would be thrown if a banned user tries to access the board because we wouldn't be within a route.

**Comment by adaur** [comment]
The ! defined part is useful after registration because the header isn't loaded yet.

**Comment by peloyeje** [comment]
My bad, I forgot to rewrite it :) (I like to rewrite rather than modify bits, but I can miss things because of that)

**Comment by adaur** [comment]
Incremental vs major rewrite approach I suppose :)

**Comment by peloyeje** [comment]
Re-added ! However I don't understand why the ! defined part is useful

**Comment by adaur** [comment]
https://github.com/featherbb/featherbb/commit/a6c33c63744545cde2c650140d864251fb03571d

Tell me if you want some changes to be added.

I reverted some changes because they broke the forum (eg the bool check in controller/header)

**Pull request closed without merging**
