### PR TITLE
New installer + Refactor middlewares

### PR DESCRIPTION
**Pull request by peloyeje**
This PR introduces a few regressions, I'll patch them asap :)

### CODE REVIEW

**Comment by peloyeje** [comment]
I'm currently patching minor issues, don't worry

**Comment by peloyeje** [comment]
Ready to review

**Comment by adaur** [comment]
I added a .htaccess_.dist_ because if you have a .htaccess and mod_rewrite disabled, it ends up with a 500 error.

**Comment by peloyeje** [comment]
Yup, I know, but I can't get the rename function to work properly .. So I choose to remove it for the time being and force the .htaccess in development (as we all have mod_rewrite). It's on my TODO :)

**Comment by peloyeje** [comment]
Ideas are welcomed :)

**Comment by peloyeje** [comment]
Workaround ;)

**Comment by adaur** [comment]
Well, I tested my code (with the rename feature) a couple of times and it worked fine: 

https://github.com/featherbb/featherbb/blob/master/install/index.php#L1766

One more thing: you should rebuild (ie remove or edit) the popup in admin/index warning about the /install folder being present.

**Comment by peloyeje** [comment]
All right, i'll edit the admin popup !
Regarding the HTML description, I choose to "authorize" HTML rendering during the page loading as the description is actually set by the admin himself.
Here what's happening during the "new" install process : the admin can input some HTML code in the install form, which is then escaped and stored in the database (you might double-check it in the config table), and finally rendered "as-is" (unescaped) in the header.
What do you think ?

**Comment by peloyeje** [comment]
Did you spot any bug in the install process ?

**Pull request merged**
