### PR TITLE
JS fade in/out for flash messages

### PR DESCRIPTION
**Pull request by beaver-dev**
Don't know why it can't be merged automatically... But there it is !
Flash messages now display on top-right corner of page, fixed position in CSS so that it is always visible even if user don't see top of page (e.g. after posting a new message, page scrolls to bottom).
Simple JS fade in effect when message is created, and fade out when clicking on the top-right close button.

### CODE REVIEW

**Comment by adaur** [comment]
I applied your changes locally and I think you didn't commit all your changes, or I missed something:

fade

I can see the message at the same position fading in and deleting itself if I click on the cross, but it doesn't appear on the top-right :/

**Comment by peloyeje** [comment]
It works locally for me, weird ... What is the purpose of onVisibilityChange and Viewport function ?

**Comment by peloyeje** [comment]
Make sure your cache is cleared

**Comment by beaver-dev** [comment]
It doesn't display at the right place for you @adaur because you don't use FeatherBB default theme seeing your screenshot. And of course I didn't write CSS in all themes stylesheets, but only default :P
Patch tomorrow, or if you can do it before me : copy style from [FeatherBB style](https://github.com/beaver-dev/featherbb/commit/c291979af2b7b21a6218a7f24692b646dc14ec1f#diff-7d1476942eced8283b0d38fd6369b418) to other themes stylesheets.
@capkokoon : onVisibilityChange & Viewport were added because at first I wanted to put the alert box in top right only if the original was hidden. These functions were in charge to detect if default message div was visible after scrolling, and add/remove a "top-right" class consequently. But eventually it seemed a bit unstable, I didn't want to spend too much time on this detail, and always placing it top-right is fine ! So indeed they can be removed, as well as script tags in headers views.
Patch tomorrow with the themes thing :)

**Comment by adaur** [comment]
Done: https://github.com/featherbb/featherbb/commit/1aff4aad38cebc10bead8b81aa9ca57fbfd41fb7

I changed the msg div to msgflash because the original messages were broken.

I restored the no-JS version for classic themes. Unless you want to work on it, I don't think they need the JS feature ;)

**Pull request closed without merging**
