### PR TITLE
Implement urlFor method to get views urls

### PR DESCRIPTION
**Pull request by peloyeje**
Here we go ! Sorry

### CODE REVIEW

**Comment by peloyeje** [comment]
I've refactored most of the links in the controllers, but when doing so, I figured out that Slim doesn't accept empty parameters when generating a URL. An example : the admin index route has an optional action parameter :

> $feather->get('(/action/:action)(/)', '\controller\admin\index:display')

However, when calling the urlFor method with no action param, the generated URL is (normal behavior as regex are called) : 

> /admin/action/:action/

Even though the URL works, it is quite ugly ... I think that the underlying problem lies in how each controller is built : it may be better to write a function for an action, rather than "wildcard" functions like \controller\viewtopic:action(), and then build specific routes for each one of them. What do you think ?

**Comment by adaur** [comment]
That's a pity. Maybe we could tweak Slim a bit?

Or you could indeed write a route per parameter, but it would take you quite a long time :)

**Comment by peloyeje** [comment]
We could, but imho it would not be a good fix because any Slim update will break the routing system ...
I was rather thinking about refactoring controllers (which atm stick to the old procedural architecture) to group methods by "objects" (post, forum, topic) or "modules" (moderate, register, login).

For instance, the moderate controller would have simple method like move_topic, delete_topic (so would the model), and a route for each method (more customizable). Were you planning on doing something similar ? I'm a beginner in OOP and MVC programming, so maybe this is not the recommended way to structure the codebase, but it seems logical to me

**Comment by adaur** [comment]
You are right. Controllers are a simple copy/paste from original files at the moment. I realized it was not the proper way to do this when I created profile, moderate and search controllers for example.

They will have to be refactored, but I'm not sure how to handle this right now...

I'm a beginner as well btw ;)

**Pull request closed without merging**
