### PR TITLE
Test urlFor method

### PR DESCRIPTION
**Pull request by peloyeje**
What about using the Slim urlFor helper method to generate the links rather than a custom made one (functional though) ?

### CODE REVIEW

**Comment by adaur** [comment]
That would be much cleaner indeed! There is a lot of changed to be made, though.

I'm not against changing them all, but I'm focused on the DB layer right now.

I will update these once I'm finished, but feel free to PR if you have time :)

Thanks for your interest.

**Comment by peloyeje** [comment]
I can do that :)

I'll try to do a proper implementation ol Slim cookie methods too

**Comment by adaur** [comment]
Amazing :)

I thought I would implement them, but they'll be removed in Slim v3 I think :(

**Comment by adaur** [comment]
One more thing: is it possible to keep the "/" ending? I like it

**Comment by peloyeje** [comment]
Yes of course !

**Comment by peloyeje** [comment]
Still trying to figure out how GitHub works, I'm struggling a bit :)
I'm going to open a new, cleaner PR haha. You may close this one ! Thx

Concerning the "/" ending, I think it's kept by default, but more testing is required (with various system configurations)

**Comment by adaur** [comment]
Don't worry, it's a bit awkward at the beginning but it gets easier after.

Thanks for your dedication :)

**Pull request closed without merging**
