### PR TITLE
Implement CSRF token protection

### PR DESCRIPTION
**Pull request by peloyeje**
#23

### CODE REVIEW

**Comment by peloyeje** [comment]
Here we go again !

**Comment by adaur** [comment]
I just tested it, perfect :+1: 

Many thanks!

**Comment by adaur** [comment]
Should we apply feather_escape to $token and $this->key?

**Comment by peloyeje** [comment]
I don't think it's necessary because $token is only retrieved from SESSION (which can't be tampered by the user, am I right ?). $this->key is set in index.php, and can't be edited as well

**Pull request merged**
